### ISSUE TITLE
Is it possible to connect using unix:socket

### ISSUE THREAD

**Issue by ovresko** [WebwareForPython/DBUtils#37]
I'm trying to connect throw unix socket, in localhost using connection pool.
is that possible ?

**Comment by Cito** [comment]
You mean a Unix domain socket? Sure, but this has nothing to do with DbUtils. Usually this happens if you do not specify a hostname (i.e. not "localhost", just empty or None) or specity a file path for the domain socket. First try to create such a connection without DbUtils, then use the same connection parameters with DbUtils.
