### ISSUE TITLE
Using use_pure = False causes error during mysql connection creation

### ISSUE THREAD

**Issue by tdv78** [WebwareForPython/DBUtils#41]
In current version use_pure argument causes error

File "/Users/tdv78/Library/Mobile Documents/com~apple~CloudDocs/Programming/progv3/progv3/venv/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 246, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
TypeError: function takes at most 20 keyword arguments (25 given)

use_pure = True fixes the problem, but it is much slower than use_pure. Previous version was ok with use_pure = False

**Comment by Cito** [comment]
I doubt this has anything to do with DBUtils. The error appears in the MySQL connector.

If you still think there is a problem in how DBUtils is passing arguments, we need example code and versions of operating system, Python, MySQL Connector, DBUtils etc. to be able to reproduce it.

For debugging, you can try to add a print statement that prints the `cnx_kwargs` before line 246 of that Python file and then have a look which are those superfluous keyword arguments (20 are expected, but 25 given!), by comparing with the signature of the C function [here](https://github.com/mysql/mysql-connector-python/blob/72707468a74ebf378308f34b158b23a71829d31b/src/mysql_capi.c#L1192).

**Comment by tdv78** [comment]
OS MacOS Monterrey 12.4, Python 3.9, DBUtils 3.0.2, MySQL Connector 8.0.29, Mysql version 8.0.26


import mysql.connector
from dbutils.pooled_db import PooledDB

def db_connect():
    host = 'localhost'
    user = 'root'
    password = 'password'
    db = 'database'
    pool = PooledDB(creator=mysql.connector, host=host, user=user, password=password, database=db, use_pure=False)
    return pool.connection()


db = db_connect()
cursor = db.cursor()


cnx_kwargs:


{'host': 'localhost', 'user': 'root', 'password': 'password', 'password1': '', 'password2': '', 'password3': '', 'database': 'database', 'port': 3306, 'client_flags': 1286669, 'unix_socket': None, 'compress': False, 'ssl_disabled': False, 'conn_attrs': {'_connector_name': 'mysql-connector-python', '_connector_license': 'GPL-2.0', '_connector_version': '8.0.29', '_source_host': 'MacBook-Pro-tdv78.local'}, 'local_infile': False, 'load_data_local_dir': None, 'oci_config_file': None, 'fido_callback': None, 'ssl_ca': None, 'ssl_cert': None, 'ssl_key': None, 'ssl_cipher_suites': None, 'tls_versions': None, 'tls_cipher_suites': None, 'ssl_verify_cert': False, 'ssl_verify_identity': False}

**Comment by tdv78** [comment]
Both MySQL and connector upgraded to 8.0.29 - no result. Please help

**Comment by Cito** [comment]
Ok, thanks, this helped me to reconstruct your use case. I have used the same versions, but Windows instead of MacOS. However, I do not get any error. The code runs fine, I can execute queries from the database. I get the same 25 `cnx_kwargs` as you, and when they are passed to the C extension there in line 246, everything works, there is no TypeError.

So what I believe is that there is something foul with your MySQL connector installation. Maybe you have an older version of the C extension that does not match the currently installed Python version. Did you try using the mysql.connector without DBUtils? Does that work? Can you try to recreate your virtualenv? Maybe there is some leftover of an old C extension, but your newer installation could not compile the new version of the C extension.

**Comment by tdv78** [comment]
Thank you!
I shall try to reinstall connector or recreate a new venv.

**Comment by tdv78** [comment]
Problem solved after I removed mysql-connector from installed packages. After reinstallation everything works. Thank you!
