### ISSUE TITLE
why  call stored procedure, Obtain output parameters sometimes None?

### ISSUE THREAD

**Issue by KissMeInTheDark** [WebwareForPython/DBUtils#9]
- os : Ubuntu16.4,
- python : 3.6,
- pymysql : 0.9.2,
- mysql : 5.7.23,
- dbutils: 1.3,

PROCEDURE code is :
```
CREATE DEFINER=`root`@`%` PROCEDURE `P_TEST`(OUT aCode varchar(4), OUT aMsg 
    varchar(16), IN aAppName varchar(16))
COMMENT 'test'
BEGIN
    set aCode = '1';
    set aMsg = 'err_msg';
    select aAppName;
END
```
and python code is :
```
def executeProc(aProcName, aParams):
tmpDbConn = None
tmpCursor = None
try:
    tmpListData = list(aParams)
    tmpListData.insert(0, '')
    tmpListData.insert(0, '')
    aParams = tuple(tmpListData)
    print(aProcName, aParams)

    tmpDbConn = DBPools.connection()
    tmpCursor = DBPools.connection().cursor()
    tmpCursor.callproc(aProcName, aParams)
    tmpDatas1 = tmpCursor.fetchall()
    print(tmpDatas1)
    tmpCursor.execute('select @_%s_0, @_%s_1 ;' % (aProcName, aProcName))
    tmpDatas2 = tmpCursor.fetchall()
    print(tmpDatas2)
    code = tmpDatas2[0][0]
    msg = tmpDatas2[0][1]
    tmpCursor.close()
    tmpDbConn.close()
    return (code, msg, tmpDatas1)
except InternalError as e:
    print(e)
    return (sqlServerInternalError, all_code[sqlServerInternalError])
except ProgrammingError as e:
    print(e)
    return (sqlServerProgrammingError, all_code[sqlServerProgrammingError])
except InterfaceError as e:
    print(e)
    return (sqlServerConnectFail, all_code[sqlServerConnectFail])
except OperationalError as e:
    print(e)
    return (sqlServerInterfaceError, all_code[sqlServerInterfaceError])
except Exception as e:
    print(e)
    return (sqlServerException, all_code[sqlServerException])
finally:
    if tmpCursor:
        tmpCursor.close()
    if tmpDbConn:
        tmpDbConn.close()

if __name__ == "__main__":
    for i in range(100):
        executeProc('P_TEST', ('a'))
````

and test result is:

P_TEST ('', '', 'a')
(('a',),)
(('1', 'err_msg'),)
P_TEST ('', '', 'a')
(('a',),)
look here : **((None, None),)**
P_TEST ('', '', 'a')
(('a',),)
look here : **((None, None),)**
P_TEST ('', '', 'a')
(('a',),)
(('1', 'err_msg'),)
P_TEST ('', '', 'a')
(('a',),)
(('1', 'err_msg'),)

This is just a random occurrence. Where is the problem? Thanks!

**Comment by KissMeInTheDark** [comment]
Sure ! like this...
```
import MySQLdb, logging, LOGUtils
from DBUtils.PooledDB import PooledDB
import Config

_myLog = logging.getLogger('LOG-XHXWEIGHT')

DBPools = PooledDB(creator=MySQLdb, mincached=0, maxcached=Config.maxcached, maxusage=Config.maxusage,
                   host=Config.DBHOST,
                   port=Config.DBPORT,
                   user=Config.DBUSER,
                   passwd=Config.DBPWD,
                   db=Config.DBNAME,
                   use_unicode=False,
                   charset=Config.DBCHAR)

```
Thanks a lot. Thank you ever so much !

**Comment by Cito** [comment]
Some things that come to my mind:
* You need to specify `Config.maxcached` and `Config.maxusage` to make this reproducable. Though I think this is not the causing the issue here.
* You should set `mincached` to some positive number, otherwise the pool will not have a useful effect.
* Just a naming issue, call it something like `dbpool` instead of `DBPools` to make it clear that it's only *one* pool, and that it's not a class, but an instance.
* You're calling `DBPools.connection()` twice. Don't do that. Call it once, store the connection as `tmpDbConn`, and then use *that*  `tmpDbConn` to get the cursor.
* You should close the cursor after getting the first result, and then reopen it before executing the select, i.e. `tmpCursor.close(); tmpCursor = tmpDbConn.cursor()`. I believe otherwise [this](https://dev.mysql.com/doc/refman/8.0/en/commands-out-of-sync.html) could cause problems (though actually I would expect an error of that kind to be printed).

Let me know if this helps.

**Comment by KissMeInTheDark** [comment]
Thank you so much! It works ! Sorry, My English is not very good. I use translation software to communicate with you. 
What I found seemed to be the problem of "maxusage", It has nothing to do with "mincached" and "maxcached"

I set mincached = 5, and maxcached = 100,
I try 100 tests, index from 0 to 99

- when maxusage = 0
fail index is []

- when maxusage = 1
fail all

- when maxusage = 2
fail index is []

- when maxusage = 3
fail index is [5, 6, 7, 8, 9, 20, 21, 22, 23, 24, 35, 36, 37, 38, 39, 50, 51, 52, 53, 54, 65, 66, 67, 68, 69, 80, 81, 82, 83, 84, 95, 96, 97, 98, 99]

- when maxusage = 4
fail index is []

- when maxusage = 5
fail index is [10, 11, 12, 13, 14, 35, 36, 37, 38, 39, 60, 61, 62, 63, 64, 85, 86, 87, 88, 89]

- when maxusage = 7
fail index is [15, 16, 17, 18, 19, 50, 51, 52, 53, 54, 85, 86, 87, 88, 89]

- when maxusage = 9
fail index is [20, 21, 22, 23, 24, 65, 66, 67, 68, 69]

- when maxusage = 11
fail index is [25, 26, 27, 28, 29, 80, 81, 82, 83, 84]

- when maxusage = 33
fail index is [80, 81, 82, 83, 84]

- when maxusage = 39
fail index is [95, 96, 97, 98, 99]

- when maxusage = 41
fail index is []

> The conclusion is that

1. No matter how many executions, the results are the same.
2. When x is an odd number, there's a problem.
3. It seems quite regular.

**Comment by Cito** [comment]
Translation software really has come a long way. It's great that it helps people all over the world to communicate.

Thanks for the detailed feedback - now I understand what happened. Yes, it has to do with `maxusage`. If you set it to a positive value, then DBUtils tries to recreate the connection after so many usages. However, MySQL obviously does not like this to happen in between calling a stored procedure and selecting the results of the same procedure.

Generally, you should wrap your transactions in begin() and commit() when using DBUtils (the begin() is normally implicit in DB API 2) so that DBUtils does not reconnect in the middle of a transaction. Unfortunately, even if you do that, it does not help in this case. I will fix this, probably by allowing the automatic reconnection to happen only before a begin() and after a commit() or rollback(). I will leave this issue open as a reminder.

For the time being, you should set maxusage=0 or create two pools, one for the normal queries (which can have maxusage > 0) and one for operations which span more than one command.
